
;;;; -*- Mode: LISP; Syntax: ANSI-Common-Lisp -*-----------------------------
;;;; NOTE: This Common LISP file was generated by c2lisp
;;;; ===== on "Aug 25 1999" "05:10:43"
;;;; Changes done directly to this file will be lost!
;;;; ------------------------------------------------------------------------


  (in-package  :plob)

;;;; --------------------------------------------------------------------------
;;;; For further comments look into file plobadmin.h
;;;; --------------------------------------------------------------------------


  (define-foreign-function
            #.C2L_BOOL
           	"fnClientCreateDatabase"
           	 #.(read-from-string    "c-sh-create-database")
      
		 ( (szURL    #.:const-c-string           :vector-in)
                   ))    ;


  (define-foreign-function
            #.C2L_BOOL
           	"fnClientExit"
           	 #.(read-from-string    "c-sh-exit")
      
		 ( (szURL    #.:const-c-string           :vector-in)
             

		   (bForceExit    #.C2L_BOOL      :value-in)
                   ))    ;


  (define-foreign-function
            #.C2L_BOOL
           	"fnClientDbReset"
           	 #.(read-from-string    "c-sh-reset")
      
		 ( (szURL    #.:const-c-string           :vector-in)
             

		   (bForceReset    #.C2L_BOOL      :value-in)
                   ))    ;


  (define-foreign-function
            #.C2L_BOOL
           	"fnClientRestart"
           	 #.(read-from-string    "c-sh-restart")
      
		 ( (szURL    #.:const-c-string           :vector-in)
             

		   (bForceRestart    #.C2L_BOOL      :value-in)
                   ))    ;

