/*-
 * Copyright (c) 1992, 1993, 1994 Henry Spencer.
 * Copyright (c) 1992, 1993, 1994
 *	The Regents of the University of California.  All rights reserved.
 *
 * This code is derived from software contributed to Berkeley by
 * Henry Spencer.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *	This product includes software developed by the University of
 *	California, Berkeley and its contributors.
 * 4. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 *	@(#)regerror.c	8.4 (Berkeley) 3/20/94
 *
 * $Header$
 */

/* ----------------------------------------------------------------------- */
#include	<stdio.h>
#include	<stdlib.h>
#include	<string.h>
#include	<time.h>
#if	!WIN32
#include	<unistd.h>
#endif
#include	"global.h"
#include	"trmalloc.h"
#include	"hash.h"
#include	"generic.h"
#include	"postore.h"
#include	"plob.h"
#include	"plobintern.h"

MODULE ( __FILE__ );

#if !WIN32 && !SOLARIS
#include <sys/cdefs.h>
#endif

#include <sys/types.h>
#include <limits.h>
#include <stdlib.h>
#include "plobregex.h"

#if !WIN32 && !SOLARIS
#include "utils.h"
#endif

/* ========= begin header generated by ./mkh ========= */
#ifdef __cplusplus
extern "C" {
#endif

/* === regerror.c === */
static char *regatoi(const regex_t *preg, char *localbuf);

#ifdef __cplusplus
}
#endif
/* ========= end header generated by ./mkh ========= */
/*
 = #define	eregNoMatch	 1
 = #define	eregBadPat	 2
 = #define	eregECollate	 3
 = #define	eregECType	 4
 = #define	eregEEscape	 5
 = #define	eregESubreg	 6
 = #define	eregEBrack	 7
 = #define	eregEParen	 8
 = #define	eregEBrace	 9
 = #define	eregBadBr	10
 = #define	eregERange	11
 = #define	eregESpace	12
 = #define	eregBadRpt	13
 = #define	eregEmpty	14
 = #define	eregAssert	15
 = #define	eregInvArg	16
 = #define	eregAtoI	255	// convert name to number (!)
 = #define	eregItoA	0400	// convert number to name (!)
 */
static struct rerr {
	int code;
	char *name;
	char *explain;
} rerrs[] = {
	{eregNoMatch,	"eregNoMatch",	"regexec() failed to match"},
	{eregBadPat,	"eregBadPat",	"invalid regular expression"},
	{eregECollate,	"eregECollate",	"invalid collating element"},
	{eregECType,	"eregECType",	"invalid character class"},
	{eregEEscape,	"eregEEscape",	"trailing backslash (\\)"},
	{eregESubreg,	"eregESubreg",	"invalid backreference number"},
	{eregEBrack,	"eregEBrack",	"brackets ([ ]) not balanced"},
	{eregEParen,	"eregEParen",	"parentheses not balanced"},
	{eregEBrace,	"eregEBrace",	"braces not balanced"},
	{eregBadBr,	"eregBadBr",	"invalid repetition count(s)"},
	{eregERange,	"eregERange",	"invalid character range"},
	{eregESpace,	"eregESpace",	"out of memory"},
	{eregBadRpt,	"eregBadRpt",	"repetition-operator operand invalid"},
	{eregEmpty,	"eregEmpty",	"empty (sub)expression"},
	{eregAssert,	"eregAssert",	"\"can't happen\" -- you found a bug"},
	{eregInvArg,	"eregInvArg",	"invalid argument to regex routine"},
	{0,		"",		"*** unknown regexp error code ***"}
};

/*
 - regerror - the interface to error numbers
 = extern size_t regerror(int, const regex_t *, char *, size_t);
 */
/* ARGSUSED */
size_t		fnRegError(REGERROR errcode, const regex_t *preg,
			   char *errbuf, size_t errbuf_size)
{
  struct rerr *r;
  size_t len;
  int target = errcode &~ eregItoA;
  char *s;
  char convbuf[50];

  PROCEDURE ( fnRegError );

  if (errcode == eregAtoI)
    s = regatoi(preg, convbuf);
  else {
    for (r = rerrs; r->code != 0; r++)
      if (r->code == target)
	break;

    if (errcode&eregItoA) {
      if (r->code != 0)
	(void) strcpy(convbuf, r->name);
      else
	sprintf(convbuf, "REG_0x%x", target);
      ASSERT(strlen(convbuf) < sizeof(convbuf));
      s = convbuf;
    } else
      s = r->explain;
  }

  len = strlen(s) + 1;
  if (errbuf_size > 0) {
    if (errbuf_size > len)
      (void) strcpy(errbuf, s);
    else {
      (void) strncpy(errbuf, s, errbuf_size-1);
      errbuf[errbuf_size-1] = '\0';
    }
  }

  return(len);
}

/*
 - regatoi - internal routine to implement eregAtoI
 == static char *regatoi(const regex_t *preg, char *localbuf);
 */
static char *
regatoi(preg, localbuf)
     const regex_t *preg;
     char *localbuf;
{
  struct rerr *r;

  PROCEDURE ( regatoi );

  for (r = rerrs; r->code != 0; r++)
    if (strcmp(r->name, preg->re_endp) == 0)
      break;
  if (r->code == 0)
    return("0");

  sprintf(localbuf, "%d", r->code);
  return(localbuf);
}

/*
  Local variables:
  buffer-file-coding-system: raw-text-unix
  End:
*/
