#!/bin/sh

PATH="${PATH}:${HOME}/plob-2.09/bin"; export PATH

for f in *.dgr; do
  d=`echo "${f}"|sed 's/[.][^.]*$//'`.dvi
  latex "\def\dgrfile{${f}}\input{dgrtodvi.tex}"
  mv dgrtodvi.dvi ${d}
  dviteps -s ${d}
done
