
# 1998/02/18 HK: Makefile for GNU make and the like.
# For using nmake, call:
#     nmake -f makedos

POSTOREDIR=../..
include ../../$(ARCH)_Makefile
include ../../$(CC)_Makefile
include Makefile.all

# Local variables:
# buffer-file-coding-system: iso-latin-1-unix
# End:
