echo
echo -----     Napier C-interpreter \& Store Tools for a $ARCH  -----
echo -----                          postore                     -----
echo

#   GENERATING THE INTERPRETER AND STORE TOOLS
# start from scratch - 1st remove old executables

make clean
make

# Local variables:
# buffer-file-coding-system: iso-latin-1-unix
# End:
