(TeX-add-style-hook "identity"
 (function
  (lambda ()
    (LaTeX-add-labels
     "chap:idty"
     "sec:idrepr"
     "fig:kartei"
     "tab:kartei"
     "sec:cobjid"
     "fig:idtaxon"
     "sec:ovidrepr"
     "fig:dadr"
     "fig:indadr"
     "fig:stridval"
     "fig:stridtyp"
     "enu:stridtyp"
     "fig:exidrepr"
     "fig:stridcs"
     "fig:usridnty"
     "sec:idsur"
     "fig:suridnty"
     "sec:handle"
     "tab:exhandle"
     "equ:getobj"
     "sec:idmsys"
     "fig:noiden"
     "fig:ooiden"
     "fig:reldbref"
     "fig:oordbref"
     "fig:periden")
    (TeX-add-symbols
     "footnoterule"
     "figurename"
     "coli"
     "colii"
     "coliii"
     "pbrr"
     "figurename"))))

