(TeX-add-style-hook "main"
 (function
  (lambda ()
    (LaTeX-add-labels
     "chap:glossary")
    (TeX-add-symbols
     "nothink"
     "schrgr"
     "schrgr"
     "nextstep"
     "nextstep"
     "thisreportnumber"
     "dipldate"
     "dipldate"
     "dipldate"
     "dipldate"
     "figurefontsize"
     "figurefontsize"
     "lb"
     "nonnil"
     "nextstep"
     "nextstep"
     "nextstep"
     "pfsection"
     "pfsubsection"
     "pfsubsubsection"
     "nextstep")
    (TeX-run-style-hooks
     "fbititle"
     "dipldefs"
     "crossref"
     "timestt"
     "avb"
     "longtable"
     "epsfig"
     "babel"
     "title"
     "intro"
     "backgrnd"
     "identity"
     "arch"
     "cltodb"
     "soh"
     "plob"
     "exit"
     "bibliogr"
     "perform"))))

