#!/bin/sh

# set -vx

if [ -n "$1" ]; then
  szSubDirs="$*"
else
  szSubDirs='eref install iref userg'
fi

(
  cd ../src/include
  make -f win32/makefile doc
)

latex=pdflatex

# production use:
szPasses='1 2 3 4 5'
# szPages='oneside twoside'
szPages='twoside'

# 2005-04-19 hkirschk: Debug:
szSubDirs='userg'
# szSubDirs='iref'
# szSubDirs='eref'
# szPasses='1 3'
# szPasses='1'


for pass in ${szPasses}; do
  for dir in ${szSubDirs}; do
    for pages in ${szPages}; do
      (
        cd ${dir}/${pages}
	case "${pass}" in
	1|[34])	nice ${latex} ${dir};;
	2)	nice bibtex ${dir};;
	5)	if [ "${pages}" = "oneside" ]; then
		  cp ${dir}.pdf ../../../doc/${dir}1.pdf
		else
		  cp ${dir}.pdf ../../../doc/${dir}.pdf
		fi;;
	esac
      )
    done
  done
done

# Local variables:
# buffer-file-coding-system: raw-text-unix
# End:
