#!/bin/sh

set -vx

if [ -n "$1" ]; then
  szSubDirs="$*"
else
  szSubDirs='eref install iref userg'
fi

(
  cd ../src/include
  make -f win32/makefile doc
)

szPasses='1 2 3 4 5 6 7'
# szPasses='6 7'
for pass in ${szPasses}; do
  for dir in ${szSubDirs}; do
    for pages in oneside twoside; do
      (
        cd ${dir}/${pages}
	case "${pass}" in
	1|[34])	nice latex ${dir};;
	2)	nice bibtex ${dir};;
	5)	nice dvips -o ${dir}.ps ${dir}.dvi;;
	6)	nice ps2pdf ${dir}.ps;;
	7)	if [ "${pages}" = "oneside" ]; then
		  cp ${dir}.pdf ../../../ps/${dir}.pdf
		else
		  cp ${dir}.pdf ../../../ps/${dir}2.pdf
		fi;;
	esac
      )
    done
  done
done

# Local variables:
# buffer-file-coding-system: iso-latin-1-unix
# End:
